[author=freelancefool]
email=freelancefoolATgmailDOTcom

[id]
name = splunkBackground
version = 1.0.0

[launcher]
version = 1.0.0
description = projectHomelab Custom Background

[install]
state = enabled
build = 6

[ui]
is_visible = 1
show_in_nav = 0
label = projectHomelab Custom Background